### ISSUE TITLE
feat: /patches pagination

### ISSUE THREAD

**Issue by Axelen123** [revanced/revanced-releases-api#71]
**Is your feature request related to a problem? Please describe.**
ReVanced now has a lot more patches compared to when this project started, and the response from the `/patches` endpoint has been getting larger and larger because of it. This could potentially cause performance issues, especially on the website.

**Describe the solution you'd like**
Add pagination and/or a `maxResults` option to not return more data than necessary.

**Describe alternatives you've considered**
Adding an option to filter by package could also help with this problem, but the user would have to select a package for that.

**Urgency**
Low.

**Comment by alexandreteles** [comment]
This will require changing the infrastructure behind the `/patches` endpoint. The current approach only caches and mirrors the JSON available in the repository, meaning that we'll have to apply transformations *before* we cache in such a way that we allow clients to paginate results.

The way the endpoint works at the moment is intentional: we don't want the API to transform that specific piece of data. I'll have to look into it more carefully and get back to you.

**Comment by alexandreteles** [comment]
Please refer to #77
